"""added new row

Revision ID: 08ea5a64141c
Revises: a4bc54fb640a
Create Date: 2023-08-15 08:56:22.066064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ea5a64141c'
down_revision = 'a4bc54fb640a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('studio', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'studio')
    # ### end Alembic commands ###
