"""added new row

Revision ID: a4bc54fb640a
Revises: e73c88f84048
Create Date: 2023-08-15 08:55:52.955659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bc54fb640a'
down_revision = 'e73c88f84048'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
