"""fix date

Revision ID: ab34aaa5f624
Revises: dc08cf5a03ca
Create Date: 2023-08-15 08:46:29.301452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab34aaa5f624'
down_revision = 'dc08cf5a03ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
