"""fix datetime

Revision ID: dc08cf5a03ca
Revises: aff0a7a386e8
Create Date: 2023-08-15 08:45:37.959589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc08cf5a03ca'
down_revision = 'aff0a7a386e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
