"""fix date

Revision ID: e73c88f84048
Revises: 55ecb61875c5
Create Date: 2023-08-15 08:49:19.933997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73c88f84048'
down_revision = '55ecb61875c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
